embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"4X4\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/main.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "4X4_board"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"dropzone\"\n"
  "mask: \"cursor\"\n"
  "mask: \"cards\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -704.3333\n"
  "      y: 675.4074\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"dropzone1\"\n"
  "  }\n"
  "  data: 209.91531\n"
  "  data: 187.91066\n"
  "  data: 10.4\n"
  "}\n"
  ""
}
